title:              Data Portofolio
email:              ccastanourrego@gmail.com
description:        Carlos Personal data science & machine learning tutorials, tips and tricks
author:             carloscastau
baseurl:            ""
url:                "https://carloscastau.github.io"

# Social Profiles
twitter_username:   carloscastau
github_username:    carloscastau
facebook_username:  carloscastau
instagram_username: carloscastau 
linkedin_username:  carloscastau

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
